### ISSUE TITLE
Having issues building mysql gem in ruby 2.0.0 in Windows

### ISSUE THREAD

**Issue by bapti** [luislavena/mysql-gem#23]
I've documented the issue in this SO question http://stackoverflow.com/questions/17673612/installing-mysql-ruby-gem-in-windows-fails-using-ruby-2-0-0

However here's a quick overview - I'm running the following command from the tutorial http://blog.mmediasys.com/2011/07/07/installing-mysql-on-windows-7-x64-and-using-ruby-with-it/

```
gem install mysql --platform=ruby -- --with-mysql-dir=C:/mysql-connector-c-noinstall-6.0.2-win32
```

I get the following error

```
This could take a while...
ERROR:  Error installing mysql:
ERROR: Failed to build gem native extension.

C:/ruby200/bin/ruby.exe extconf.rb --with-mysql-dir=C:/mysql-connector-c-noinstall-6.0.2-win32 --with-mysql-lib=C:\mysql-connector-c-noinstall-6.0.2-win32\lib\libmysql.dll
checking for main() in -llibmysql... no
*** extconf.rb failed ***
```

I'm not quite sure what i'm doing wrong here.

**Comment by LellaKS** [comment]
Not able to mysql gem in ruby 2.3.3 version. My ruby version :ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]. Getting below exception:
C:\Ruby23-x64>gem install mysql
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing mysql:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql-2.9.1/ext/mysql_api
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20170123-7004-xoua5t.rb extconf.rb
checking for main() in -llibmysql... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-libmysqllib
        --without-libmysqllib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/mysql-2.9.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql-2.9.1 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/mysql-2.9.1/gem_make.out

######Attaching gem_make.out and mkmf.log file.
[gem_makeout.txt](https://github.com/luislavena/mysql-gem/files/723463/gem_makeout.txt)
[mkmflog.txt](https://github.com/luislavena/mysql-gem/files/723464/mkmflog.txt)
MY devkit version : DevKit-mingw64-64-4.7.2-20130224-1432-sfx
Would you please help me to resolve the issue?
