### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by mittalyashu** [luislavena/mysql-gem#36]
Getting this error after running this command: `gem install mysql`.

![mintty_2018-10-02_17-03-17](https://user-images.githubusercontent.com/29014463/46346545-fb9a7380-c665-11e8-8ae6-1e842277ee92.png)

I am not facing issue with other gems and I have already searched StackOverflow but didn't found any solution.

**Comment by luislavena** [comment]
Hello @mittalyashu and welcome.

The error you're receiving is because you environment lacks the dependencies necessary for this gem to install, notice the check part:

```
checking for -llibmysql... no
```

You need to install support dependencies like libmysql-dev in order for the gem to compile.

PS: please note that this project **has no maintainer** (and still looking for one). I will recommend check any documentation provided by the Ruby distribution you're using on how to install these dependencies.
